config/routes.rb
Rails.application.routes.draw do

  resources :bookings
  resources :sharespaces
  resources :photos
  resources :albums
  resources :sharespace_venues
  resources :addresses
  resources :charges
  resources :reviews

  devise_for :users
  resources :users


  get 'profile', to: 'users#profile'
  get 'admin', to: 'users#admin'
  get 'reserved_booking', to: 'bookings#reserved'


  post '/search', to: 'sharespace_venues#index'
  get '/search', to: 'sharespace_venues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#home'

end

app/models/sharespace_venue.rb
class SharespaceVenue < ApplicationRecord
  resourcify

  belongs_to :user
  has_one :address, as: :addressable

  has_many :photos, as: :photoable
  has_many :reviews, as: :reviewable



  has_many :sharespaces

  after_create :tasks

  private
  def tasks
    set_address
    UserNotifierMailer.send_listing_creation_email(self.user).deliver
  end

  def set_address
    self.build_address.save
  end
end

app/controllers/sharespace_venues_controller.rb
class SharespaceVenuesController < ApplicationController
  before_action :set_sharespace_venue, only: [:show, :edit, :update, :destroy]

  # GET /sharespace_venues
  # GET /sharespace_venues.json
  def index


    if params[:address] != nil
      @addresses = Address.near(params[:address], 50, order: 'distance').where(addressable_type: "SharespaceVenue")
      @current_loc = params[:address]
      @nearest_me = @addresses[0].addressable
    else
      @addresses = Address.where(addressable_type: "SharespaceVenue")
    end
    rescue
      flash[:notice] = "Sorry couldn't find a store near you."
  end

  # GET /sharespace_venues/1
  # GET /sharespace_venues/1.json
  def show
  end

  # GET /sharespace_venues/new
  def new
    authorization("create")
    @sharespace_venue = SharespaceVenue.new
  end

  # GET /sharespace_venues/1/edit
  def edit
    authorization("update", @sharespace_venu)
  end

  # POST /sharespace_venues
  # POST /sharespace_venues.json
  def create
    authorization("create")
    @sharespace_venue = SharespaceVenue.new(sharespace_venue_params)

    respond_to do |format|
      if @sharespace_venue.save
        format.html { redirect_to edit_address_path(@sharespace_venue.address), notice: 'Collab space listing was successfully created.' }
        format.json { render :show, status: :created, location: @sharespace_venue }
      else
        format.html { render :new }
        format.json { render json: @sharespace_venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sharespace_venues/1
  # PATCH/PUT /sharespace_venues/1.json
  def update
    authorization("update", @sharespace_venu)

    respond_to do |format|
      if @sharespace_venue.update(sharespace_venue_params)
        format.html { redirect_to @sharespace_venue, notice: 'Collab space listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @sharespace_venue }
      else
        format.html { render :edit }
        format.json { render json: @sharespace_venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sharespace_venues/1
  # DELETE /sharespace_venues/1.json
  def destroy
    authorization("destroy", @sharespace_venu)

    @sharespace_venue.destroy
    respond_to do |format|
      format.html { redirect_to sharespace_venues_url, notice: 'Collab space listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sharespace_venue
      @sharespace_venue = SharespaceVenue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sharespace_venue_params
      params.require(:sharespace_venue).permit(:user_id, :name, :brief_description, :description, :rules, :surrounding_area_description, :overall_rating, :cost_per_day)
    end
end

app/helpers/sharespace_venues_helper.rb
module SharespaceVenuesHelper



end

app/views/sharespace_venues/_form.html.erb
<%= semantic_form_for sharespace_venue, html: { class: "address_form" } do |f| %>


  <%= f.inputs name: "Sharespace listing.", id: "" do %>

  <%= f.input :name %>
  <%= f.input :description,  as: :text, input_html: { class: "text_box_m" } %>
  <%= f.input :rules, as: :text, input_html: { class: "text_box_m" } %>
  <%= f.input :surrounding_area_description, as: :text, input_html: { class: "text_box_m" } %>
  <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id  } %>

  <% end %>
  <%= f.actions do %>
     <%= f.action :submit, :label => "Submit.", button_html: { class: "button_fl button" }%>
   <% end %>
<% end %>

app/views/sharespace_venues/_search_address.html.erb
<%= form_tag("/search", method: "get") do %>
  <%= text_field_tag(:address, "", placeholder: "Enter an address...", class: "search_bar") %>
  <%= submit_tag("Search", class: "search_button") %>
<% end %>

<script type="text/javascript">
  function initialize() {

  var input = document.getElementById('address');
  var autocomplete = new google.maps.places.Autocomplete(input);
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/sharespace_venues/_tiles.html.erb
<% if listing.class.name == "SharespaceVenue" %>
<div class="item">
  <div class="tile_image">
    <%=  link_to (profile_photo_display(listing, "medium")), listing %>
  </div>

  <ul class="item_list">
    <li><%= link_to listing.name, listing %></li>
    <li><%= link_to address_check(listing), listing %></li>
    <li><%= price_range(listing) %></li>


    <% rating = rating_average(listing) %>
    <% if rating == "No reviews yet." %>
      <li><%= rating %></li>
    <% else %>
      <% anti_rating = 5 - rating  %>
      <li>
      <% until rating == 0 %>
        <span class='fa fa-star checked_star'></span>
        <% rating -= 1 %>
      <% end %>


      <span class="rating_num"><%= listing.reviews.count %></span>
    <% end %>
    </li>


  </ul>
</div>
<% end %>

app/views/sharespace_venues/edit.html.erb
<h1>Editing Collab Space Listing</h1>

<%= render 'form', sharespace_venue: @sharespace_venue %>

<%= link_to 'Show', @sharespace_venue %> |
<%= link_to 'Back', sharespace_venues_path %>

app/views/sharespace_venues/index.html.erb
  <div class="nav_box_ss_page">
      <%= render 'users/search_address' %>
        <%= link_to 'New Share-Space Listing', new_sharespace_venue_path, class: "new_sharespace" if user_signed_in? %>
  </div>

<% if @nearest_me %>
<p> Your closest listing is <%= link_to @nearest_me.name, @nearest_me %> in <%= @nearest_me.address.city_suburb %></p>
<% end %>
<div class="listing_layout">
<div class="listings">

  <h3>Featured Share-Spaces in your area.</h3>
  <div class="tiles">
    <% if @addresses != nil %>
      <% @addresses.each do |address| listing = address.addressable %>
        <%= render partial: 'tiles', :locals => {:listing => listing} %>
      <% end %>
    <% end %>
  </div>

  <h3>Share-Spaces.</h3>

  <div class="tiles">
    <% if @addresses != nil %>
      <% @addresses.each do |address| listing = address.addressable %>
        <%= render partial: 'tiles', :locals => {:listing => listing} %>
      <% end %>
    <% end %>
  </div>


</div>
<div id="map"></div>

</div>
   <script>
     var map;
     function initMap() {
       map = new google.maps.Map(document.getElementById('map'), {
         zoom: 15,
         <% if SharespaceVenue.first != nil && SharespaceVenue.first.address.latitude != nil %>
         center: new google.maps.LatLng(<%= SharespaceVenue.first.address.latitude %>, <%= SharespaceVenue.first.address.longitude %>),
         <% else %>
         center: new google.maps.LatLng(-27.4698, 153.0251),
         <% end %>
         mapTypeId: 'roadmap'
       });
// THIS SECTION IS FOR ICONS/Images
       var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';


// THIS SECTION IS FOR all the iterated locations

       var features = [
         <% @addresses.each do |address| %>

           <% if address.longitude != nil %>
         {
           position: new google.maps.LatLng(<%= address.latitude %>, <%= address.longitude %>),
           // <% if address.addressable.photos.first != nil %>
           // url: '<%= address.addressable.photos.first.image_url %>',
           // scaledSize : new google.maps.Size(35, 35),
           // <% end %>

         },
         <% end %>
         <% end %>
       ];

       // Create markers.
       features.forEach(function(feature) {
         var marker = new google.maps.Marker({
           position: feature.position,
           icon: {url: feature.url,
                  scaledSize : new google.maps.Size(35, 35),
                    },
           map: map
         });
       });
     }
   </script>
   <script async defer
   src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC_u77wbZStldL82_gGDInvPlanmANOyl8&callback=initMap">
   </script>
<br>

app/views/sharespace_venues/new.html.erb
<div class="form_container new_ss">
  <div class="form_render_ss_v">
    <%= render 'form', sharespace_venue: @sharespace_venue %>
    <%= link_to 'Back', sharespace_venues_path %>
  </div>
</div>

app/views/sharespace_venues/show.html.erb
<div class="main_image" >
  <%=  profile_photo_display(@sharespace_venue, "large") %>
</div>



<main class="main_section">

  <div class="tool_bar">

    <% if user_signed_in? && current_user.can_update?(@sharespace_venue) %>

      <p class="tools open_new_ss">Add a sharespace to your venue!</p>
      <p class="tools open_add_image">Add an image.</p>
      <p class="tools open_edit_address">Edit Address</p>
      <p class="tools open_edit_venue">Edit Share-Space</p>

    <% end %>
  </div>

  <div class="split_grid">
    <div class="left">
      <div class="summary listing_info">
        <p>Type-placeholder</p>
        <h1><%= @sharespace_venue.name %></h1>
        <h4><%= @sharespace_venue.address.vague_address %></h4>
        <p><%= "#{@sharespace_venue.user.first_name} #{@sharespace_venue.user.last_name}" %></p>
        <p><%= rating_average(@sharespace_venue) %></p>
      </div>
      <div class="details listing_info">
        <p>
          <strong>Description</strong>
          <%= @sharespace_venue.description %>
        </p>
      </div>

      <div class="rules listing_info">
        <p>
          <strong>Rules</strong>
          <%= @sharespace_venue.rules %>
        </p>
      </div>
      <div class="surrounding_area_description listing_info last">
        <p>
          <strong>Surrounding area</strong>
          <%= @sharespace_venue.surrounding_area_description %>
        </p>
      </div>
   </div>

    <div class="right">

      <div class="ss_section">
        <h5 style="margin: 0;">Share-Spaces</h5>
        <div class="sharespace_tiles">
          <% @sharespace_venue.sharespaces.each do |sharespace| %>
          <div class="sharespace">
            <div class="ss_image_show"><%= link_to (profile_photo_display(sharespace, "thumb_photo")), sharespace %></div>
            <h5 style="margin-bottom: 0;"><%= link_to sharespace.space_type, sharespace %></h5>
            <% if user_signed_in? %>
              <%= link_to 'Edit', edit_sharespace_venue_path(sharespace) if current_user.can_update?(@sharespace_venue) %>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>

      <td>
        <iframe
        width="100%"
        height="250"
        frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyB8sC_5Vo_Mk5YOxQ9sbeIL6dN6PQNTJus
          &q=<%= @sharespace_venue.address.full_street_address %>" allowfullscreen>
        </iframe>
      </td>

      <div class="review_section">
        <h5 style="margin: 0;">Reviews</h5>
        <div class="reviews">
          <% @sharespace_venue.reviews.order(created_at: :desc).each do |review| %>
          <div class="review">
            <h5 style="margin-bottom: 0;"><%= link_to review.reference.user.fullname, review %>
              <span class="date"><%= review.created_at.strftime("%d %b %Y") %></span></h5>

            <% review_rating = review.rating %>
            <% anti_rating = 5 - review_rating  %>

            <% until review_rating == 0 %>
              <span class='fa fa-star checked_star'></span>
              <% review_rating -= 1 %>
            <% end %>

            <% until anti_rating == 0 %>
              <span class='fa fa-star'></span>
              <% anti_rating -= 1 %>
            <% end %>

            <p><%= review.review  %></p>
            <% if user_signed_in? %>
              <%= link_to 'Edit', edit_review_path(review) if current_user.can_update?(review.reference) %>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</main>




<!-- Hidden image render -->
<div class="form_container add_image hide">
  <div class="form_render">
    <div class="button_box"><p class="close_form close_box">&times;</p></div>
    <%= render 'photos/form', photo: Photo.new, photoable_object: @sharespace_venue if user_signed_in? && current_user.can_update?(@sharespace_venue)  %>
  </div>
</div>

<!-- Hidden edit address render -->
<div class="form_container edit_address hide">
  <div class="form_render_address">
    <div class="button_box"><p class="close_form close_box">&times;</p></div>
    <%= render 'addresses/form', address: @sharespace_venue.address if user_signed_in? && current_user.can_update?(@sharespace_venue) %>
  </div>
</div>

<!-- Hidden edit sharespace_venue render -->
<div class="form_container edit_venue hide">
  <div class="form_render_ss_v">
    <div class="button_box"><p class="close_form close_box">&times;</p></div>
    <%= render 'form', sharespace_venue: @sharespace_venue if user_signed_in? && current_user.can_update?(@sharespace_venue)  %>
  </div>
</div>

<!-- Hidden new sharespace render -->
<div class="form_container new_ss hide">
  <div class="form_render">
    <div class="button_box"><p class="close_form close_box">&times;</p></div>
    <%= render 'sharespaces/form', sharespace_new: Sharespace.new, sharespace_venue: @sharespace_venue.id if user_signed_in? && current_user.can_update?(@sharespace_venue)  %>
  </div>
</div>



<div class="form_bg hide close_box">
</div>


<script>
// Closes all boxes
$(document).ready(function(){
  $(".close_box").click(function(){
    $(".form_container").addClass('hide')
    $(".form_bg").addClass('hide')
  });
});

// Image form render JS.
$(document).ready(function(){
  $(".open_add_image").click(function(){
    $(".add_image").removeClass('hide')
    $(".form_bg").removeClass('hide')
  });
});

// Adress edit form render JS.
$(document).ready(function(){
  $(".open_edit_address").click(function(){
    $(".edit_address").removeClass('hide')
    $(".form_bg").removeClass('hide')
  });
});

// Venue edit form render JS.
$(document).ready(function(){
  $(".open_edit_venue").click(function(){
    $(".edit_venue").removeClass('hide')
    $(".form_bg").removeClass('hide')
  });
});

// New sharespace form render JS.
$(document).ready(function(){
  $(".open_new_ss").click(function(){
    $(".new_ss").removeClass('hide')
    $(".form_bg").removeClass('hide')
  });
});


</script>