config/routes.rb
Rails.application.routes.draw do

  resources :bookings
  resources :sharespaces
  resources :photos
  resources :albums
  resources :sharespace_venues
  resources :addresses
  resources :charges
  resources :reviews

  devise_for :users
  resources :users


  get 'profile', to: 'users#profile'
  get 'admin', to: 'users#admin'
  get 'reserved_booking', to: 'bookings#reserved'


  post '/search', to: 'sharespace_venues#index'
  get '/search', to: 'sharespace_venues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#home'

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :address, as: :addressable

  has_many :photos, as: :photoable
  has_many :reviews, as: :reviewable
  has_many :sharespace_venues
  has_many :bookings
  has_many :collab_space_listings

  after_create :tasks


# These next methods set what the user can and cannot do.
  def admin_only
    self.has_role?(:admin)
  end

  def can_create?
    self.has_role?(:admin) || self.has_role?(:basic)
  end

  def owner?(owner)
    self.has_role?(:admin) || owner == self
  end

  def can_update?(object)
    self.has_role?(:admin) || (self.has_role?(:basic) && object.user == self)
  end

  def can_destroy?(object)
    self.has_role?(:admin) or (self.has_role?(:basic) && object.user == self) or self.has_role?(:moderator)
  end

  def fullname
    if first_name && last_name != nil
      "#{first_name} #{last_name}"
    elsif first_name != nil && last_name == nil
      "#{first_name}"
    elsif first_name == nil && last_name != nil
      "#{last_name}"
    else
      "User has no name."
   end
  end



  private
# This method runs multiple methods for the "after_create" method that runs the methods once a new user has signed up.
  def tasks
    set_address
    set_role
    UserNotifierMailer.send_signup_email(self).deliver
  end

# Sets an empty address for each new user which they can update and fill out at a later date.
  def set_address
    self.build_address.save
  end

# Adds a basic role with limited functions to a new user. Currently basic can do anything but in the futureI plan to incorporate "premium" membership roles (add_role :premium_member) if they pay a subscription.
  def set_role
    self.add_role :basic
  end



end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :create_address, only: [:new]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # creating method that creates a new address and assigns it to an instance variable as a before_action for creating a new account.
  def create_address

  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    authorization("admin")
    @users = User.all
  end

  def admin
    authorization("admin")

  end

  def home
    @addresses = SharespaceVenue.last(5)
    @featured_ss = []
    @addresses.each do |ss|
      @featured_ss.push(ss.address)
    end
  end

  def profile
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @profile_photo = @user.photos.where(profile: true)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_search_address.html.erb
<%= form_tag("/search", method: "get", class: "search_form") do %>
  <%= text_field_tag(:address, "", placeholder: "Enter an address...", class: "search_bar") %>
  <%= submit_tag("Search", class: "search_button") %>
<% end %>

<script type="text/javascript">
  function initialize() {

  var input = document.getElementById('address');
  var autocomplete = new google.maps.places.Autocomplete(input);
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/users/admin.html.erb
<h1>Admin</h1>


<%= link_to 'Share Spaces', sharespaces_path, class: "navbar-brand" %>
<%= link_to 'Share Space venues', sharespace_venues_path, class: "navbar-brand" %>
<%= link_to 'Bookings', bookings_path, class: "navbar-brand" %>
<%= link_to 'Users', users_path, class: "navbar-brand" %>
<%= link_to 'Adresses', addresses_path, class: "navbar-brand" %>
<%= link_to 'Albums', albums_path, class: "navbar-brand" %>
<%= link_to 'Photos', photos_path, class: "navbar-brand" %>
<%= link_to 'Reviews', reviews_path, class: "navbar-brand" %>

app/views/users/home.html.erb
<div class="landing_page">
  <div class="landing_image">
    <div class="blue_box">
      <h1>Share-Space</h1>
        <%= render 'search_address' %>
    </div>
  </div>
</div>

<div class="page_contents">

  <h3>Featured Share-Spaces</h3>
  <div class="tiles">
    <% if @featured_ss != nil %>
      <% @featured_ss.each do |address| listing = address.addressable %>
        <%= render partial: 'sharespace_venues/tiles', :locals => {:listing => listing} %>
      <% end %>
    <% end %>
  </div>

  <h3>Featured Projects</h3>
  <div class="tiles">
    <% if @featured_ss != nil %>
      <% @featured_ss.each do |address| listing = address.addressable %>
        <%= render partial: 'sharespace_venues/tiles', :locals => {:listing => listing} %>
      <% end %>
    <% end %>
  </div>

  <h3>Featured Blogs</h3>
  <div class="tiles">
    <% if @featured_ss != nil %>
      <% @featured_ss.each do |address| listing = address.addressable %>
        <%= render partial: 'sharespace_venues/tiles', :locals => {:listing => listing} %>
      <% end %>
    <% end %>
  </div>


</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= "#{user.first_name} #{user.last_name}" %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New user', new_user_path %>

app/views/users/profile.html.erb
<div class="profile_container_main">

  <div class="profile_grid_top">
    <div class="profile_images">
      <h2><%= @user.first_name %> <%= @user.last_name %></h2>
        <div class="rating_bar"><% 5.times do %><span class='fa fa-star checked_star'><% end %></span></div>

      <div class="profile_image open_add_image open">
        <%=  profile_photo_display(@user, "medium") %>
      </div>
    </div>

    <div class="profile_overview">
      <ul list-style: "none">
      <li>Email: <%= @user.email %></li>
      <li>DoB: <%= @user.dob %></li>
      <li>Ph: <%= @user.phone_number %></li>
      <li>Description: <%= @user.description %></li>
      <li>Address: <%= @user.address.full_street_address %></li>

      </ul>
      <p class="open_edit_address open"> Edit address </p>
      <p class="open_edit_profile open"> Edit Profile </p>



    </div>

    <div class="profile_projects">
      <h3>Projects</h3>
    </div>
  </div>



  <div class="profile_grid_bottom">
    <div class="profile_reviews">
      <h3>Reviews</h3>

    </div>

    <div class="profile_listings">
      <h3>Sharespace venues</h3>

    </div>
  </div>

</div>

<div class = "profiles">





</div>

<div class="form_container add_image hide">
  <div class="form_render">
    <div class="button_box"><p class="close_form close_box">&times;</p></div>
    <%= render 'photos/form', photo: Photo.new, photoable_object: @user if user_signed_in? && current_user.owner?(@user)  %>
  </div>
</div>

<!-- Hidden edit address render -->
<div class="form_container edit_address hide">
  <div class="form_render_address">
    <div class="button_box"><p class="close_form close_box">&times;</p></div>
    <%= link_to 'Edit Address', edit_address_path(@user.address) if user_signed_in? && current_user.owner?(@user) %>  </div>
</div>

<!-- Hidden edit sharespace_venue render -->
<div class="form_container edit_profile hide">
  <div class="form_render_ss_v">
    <div class="button_box"><p class="close_form close_box">&times;</p></div>
    <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" if user_signed_in? && current_user.owner?(@user) %>
  </div>
</div>




<div class="form_bg hide close_box">
</div>

<script>
// Closes all boxes
$(document).ready(function(){
  $(".close_box").click(function(){
    $(".form_container").addClass('hide')
    $(".form_bg").addClass('hide')
  });
});

// Image form render JS.
$(document).ready(function(){
  $(".open_add_image").click(function(){
    $(".add_image").removeClass('hide')
    $(".form_bg").removeClass('hide')
  });
});


// Adress edit form render JS.
$(document).ready(function(){
  $(".open_edit_address").click(function(){
    $(".edit_address").removeClass('hide')
    $(".form_bg").removeClass('hide')
  });
});

// Venue edit form render JS.
$(document).ready(function(){
  $(".open_edit_profile").click(function(){
    $(".edit_profile").removeClass('hide')
    $(".form_bg").removeClass('hide')
  });
});

// New sharespace form render JS.
$(document).ready(function(){
  $(".open_new_ss").click(function(){
    $(".new_ss").removeClass('hide')
    $(".form_bg").removeClass('hide')
  });
});
</script>

app/views/users/search.html.erb
<div style="margin-left: 30px;">

  <h1>Collab Space Listings</h1>
  <% @sharespace_venues.each do |listing| %>


  <h4 style=""><%= link_to listing.name, listing %></h4>
  <p style=""><%=  listing.address.full_street_address%></p>


  <% end %>

</div>

app/views/users/show.html.erb
<div class = "profiles">
<h1><%= @user.first_name %> <%= @user.last_name %><h1>
<h2>Profile</h2>
<div><%= profile_photo_display(@user,"profile_photo") %></div>
<p><%= rating_average(@user) %></p>
<ul list-style: "none">
<li>Email: <%= @user.email %></li>
<li>DoB: <%= @user.dob %></li>
<li>Ph: <%= @user.phone_number %></li>
<li>Description: <%= @user.description %></li>
<li>Address: <%= @user.address.full_street_address %></li>

</ul>

<h3> Upload an awesome photo for your awesome life!</h3>
<%= render 'photos/form', photo: Photo.new, photoable_object: @user if current_user.owner?(@user)  %>
<%= link_to 'Edit Address', edit_address_path(@user.address) if current_user.owner?(@user) %>
<%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" if current_user.owner?(@user) %>
</div>