config/routes.rb
Rails.application.routes.draw do

  resources :bookings
  resources :sharespaces
  resources :photos
  resources :albums
  resources :sharespace_venues
  resources :addresses
  resources :charges
  resources :reviews

  devise_for :users
  resources :users


  get 'profile', to: 'users#profile'
  get 'admin', to: 'users#admin'
  get 'reserved_booking', to: 'bookings#reserved'


  post '/search', to: 'sharespace_venues#index'
  get '/search', to: 'sharespace_venues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#home'

end

app/models/address.rb
class Address < ApplicationRecord
  resourcify
  geocoded_by :full_street_address
  belongs_to :addressable, polymorphic: true, optional: true
  after_validation :geocode

  def full_street_address
    if city_suburb && state != nil
      "#{address_line_one}, #{city_suburb}, #{state}"
    end
  end

  def vague_address
    if city_suburb && state != nil
    "#{city_suburb}, #{state}"
    else
      nil
    end
  end
end

app/models/album.rb
class Album < ApplicationRecord
  resourcify
end

app/models/booking.rb
class Booking < ApplicationRecord
  resourcify
  belongs_to :user
  belongs_to :sharespace

  has_many :reviews, as: :reviewable

  after_create :tasks_on_create

  def tasks_on_create
    cost_days_math
    set_paid_status
    set_reviewed_status
  end

  private

  def set_paid_status
    if self.total_cost == 0 or self.total_cost == nil
      self.update(paid: true)
    else
      self.update(paid: false)
    end
  end

  def set_reviewed_status
    self.update(host_reviewed: false, user_reviewed: false) if self != nil
  end

  def cost_days_math
    total_days = (self.date_to - self.date_from).to_i + 1
    total_cost = self.sharespace.cost * total_days if self.sharespace.cost != nil
    self.update(total_days: total_days, total_cost: total_cost)
  end


end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :sharespace_venue
end

app/models/industry.rb
class Industry < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  belongs_to :industry
end

app/models/perk.rb
class Perk < ApplicationRecord
  belongs_to :sharespace_venue
end

app/models/photo.rb
class Photo < ApplicationRecord
  resourcify
  mount_uploader :image, PhotoImageUploader
  belongs_to :photoable, polymorphic: true, optional: true

  after_create :tasks

  def tasks
    profile_check
  end

  def profile_check
      if self.photoable.photos.count <= 1
        self.photoable.update(profile_photo: self.id)
      end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  resourcify
  belongs_to :reviewable, polymorphic: true, optional: true
  belongs_to :reference, polymorphic: true, optional: true
  after_create :tasks


  private
  def tasks
    set_reviewed_status
  end

  def set_reviewed_status
    if self.reference_type == 'Booking' && self.reference != nil
      self.reference.update(host_reviewed: true) if self.reviewable_type == 'SharespaceVenue'
      self.reference.update(user_reviewed: true) if self.reviewable_type == 'User'
    end
  end

end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/school.rb
class School < ApplicationRecord
end

app/models/sharespace.rb
class Sharespace < ApplicationRecord
  resourcify
  belongs_to :sharespace_venue
  has_many :photos, as: :photoable
  has_many :bookings


end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :address, as: :addressable

  has_many :photos, as: :photoable
  has_many :reviews, as: :reviewable
  has_many :sharespace_venues
  has_many :bookings
  has_many :collab_space_listings

  after_create :tasks


# These next methods set what the user can and cannot do.
  def admin_only
    self.has_role?(:admin)
  end

  def can_create?
    self.has_role?(:admin) || self.has_role?(:basic)
  end

  def owner?(owner)
    self.has_role?(:admin) || owner == self
  end

  def can_update?(object)
    self.has_role?(:admin) || (self.has_role?(:basic) && object.user == self)
  end

  def can_destroy?(object)
    self.has_role?(:admin) or (self.has_role?(:basic) && object.user == self) or self.has_role?(:moderator)
  end

  def fullname
    if first_name && last_name != nil
      "#{first_name} #{last_name}"
    elsif first_name != nil && last_name == nil
      "#{first_name}"
    elsif first_name == nil && last_name != nil
      "#{last_name}"
    else
      "User has no name."
   end
  end



  private
# This method runs multiple methods for the "after_create" method that runs the methods once a new user has signed up.
  def tasks
    set_address
    set_role
    UserNotifierMailer.send_signup_email(self).deliver
  end

# Sets an empty address for each new user which they can update and fill out at a later date.
  def set_address
    self.build_address.save
  end

# Adds a basic role with limited functions to a new user. Currently basic can do anything but in the futureI plan to incorporate "premium" membership roles (add_role :premium_member) if they pay a subscription.
  def set_role
    self.add_role :basic
  end



end

app/controllers/sharespaces_controller.rb
class SharespacesController < ApplicationController
  before_action :set_sharespace, only: [:show, :edit, :update, :destroy]

  # GET /sharespaces
  # GET /sharespaces.json
  def index
    authorization("admin")
    @sharespaces = Sharespace.all
  end

  # GET /sharespaces/1
  # GET /sharespaces/1.json
  def show
  end

  # GET /sharespaces/new
  def new
    authorization("create")
    @sharespace = Sharespace.new
  end

  # GET /sharespaces/1/edit
  def edit
    authorization("update", @sharespace)
  end

  # POST /sharespaces
  # POST /sharespaces.json
  def create
    authorization("create")

    @sharespace = Sharespace.new(sharespace_params)

    respond_to do |format|
      if @sharespace.save
        format.html { redirect_to  @sharespace, notice: 'Sharespace was successfully created.' }
        format.json { render :show, status: :created, location: @sharespace }
      else
        format.html { render :new }
        format.json { render json: @sharespace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sharespaces/1
  # PATCH/PUT /sharespaces/1.json
  def update
    authorization("update", @sharespace)

    respond_to do |format|
      if @sharespace.update(sharespace_params)
        format.html { redirect_to @sharespace, notice: 'Sharespace was successfully updated.' }
        format.json { render :show, status: :ok, location: @sharespace }
      else
        format.html { render :edit }
        format.json { render json: @sharespace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sharespaces/1
  # DELETE /sharespaces/1.json
  def destroy
    authorization("destroy", @sharespace)

    @sharespace.destroy
    respond_to do |format|
      format.html { redirect_to sharespaces_url, notice: 'Sharespace was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sharespace
      @sharespace = Sharespace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sharespace_params
      params.require(:sharespace).permit(:space_type, :description, :cost, :sharespace_venue_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/form_helper.rb
module FormHelper
  def set_listing_address(collab_space)
    collab_space.address ||= Address.new
    collab_space
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sharespaces_helper.rb
module SharespacesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/sharespaces/_form.html.erb
<%= semantic_form_for sharespace_new, html: { class: "address_form" } do |f| %>


  <%= f.inputs name: "New Share space", id: "" do %>

  <%= f.input :space_type %>
  <%= f.input :description,  as: :text, input_html: { class: "text_box_m" } %>
  <%= f.input :cost %>
  <%= f.input :sharespace_venue_id, as: :hidden, input_html: { value: sharespace_venue  } %>


  <% end %>
  <%= f.actions do %>
     <%= f.action :submit, :label => "List your venue.", button_html: { class: "button_fl button" }%>
   <% end %>
<% end %>

app/views/sharespaces/edit.html.erb
<h1>Editing Sharespace</h1>

<%= render 'form', sharespace: @sharespace %>

<%= link_to 'Show', @sharespace %> |
<%= link_to 'Back', sharespaces_path %>

app/views/sharespaces/index.html.erb
<h1>Sharespaces</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Share space listing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sharespaces.each do |sharespace| %>
      <tr>
        <td><%= sharespace.space_type %></td>
        <td><%= sharespace.description %></td>
        <td><%= sharespace.cost %></td>
        <td><%= sharespace.sharespace_venue %></td>
        <td><%= link_to 'Show', sharespace %></td>
        <td><%= link_to 'Edit', edit_sharespace_path(sharespace) %></td>
        <td><%= link_to 'Destroy', sharespace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sharespace', new_sharespace_path %>

app/views/sharespaces/new.html.erb
<h1>New Sharespace</h1>

<%= render 'form', sharespace: @sharespace %>

<%= link_to 'Back', sharespaces_path %>

app/views/sharespaces/show.html.erb
<p id="notice"><%= notice %></p>

<%= profile_photo_display(@sharespace, "profile_photo") %>
<p>
  <strong>Type:</strong>
  <%= @sharespace.space_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sharespace.description %>
</p>
<p>
  <% if @sharespace.cost != nil or @sharespace.cost == 0  %>
    <strong>Cost:</strong>
    <%= @sharespace.cost %>
  <% else %>
    <strong>Free</strong>
  <% end %>
</p>

<p>
  <strong>Share space listing:</strong>
  <%= @sharespace.sharespace_venue.name %>
</p>
<% if user_signed_in? %>
  <%= render 'photos/form', photo: Photo.new, photoable_object: @sharespace if current_user.can_update?(@sharespace.sharespace_venue) %>

  <%= link_to 'Make a Booking', new_booking_path(params:{sharespace_id: @sharespace.id}) if current_user.bookings.where(paid:false).count == 0 %>

  <%= link_to 'Edit', edit_sharespace_path(@sharespace) if current_user.can_update?(@sharespace.sharespace_venue) %>
<% end %>

<%= link_to 'Back', @sharespace.sharespace_venue %>