config/routes.rb
Rails.application.routes.draw do

  resources :bookings
  resources :sharespaces
  resources :photos
  resources :albums
  resources :sharespace_venues
  resources :addresses
  resources :charges
  resources :reviews

  devise_for :users
  resources :users


  get 'profile', to: 'users#profile'
  get 'admin', to: 'users#admin'
  get 'reserved_booking', to: 'bookings#reserved'


  post '/search', to: 'sharespace_venues#index'
  get '/search', to: 'sharespace_venues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#home'

end

app/models/address.rb
class Address < ApplicationRecord
  resourcify
  geocoded_by :full_street_address
  belongs_to :addressable, polymorphic: true, optional: true
  after_validation :geocode

  def full_street_address
    if city_suburb && state != nil
      "#{address_line_one}, #{city_suburb}, #{state}"
    end
  end

  def vague_address
    if city_suburb && state != nil
    "#{city_suburb}, #{state}"
    else
      nil
    end
  end
end

app/models/album.rb
class Album < ApplicationRecord
  resourcify
end

app/models/booking.rb
class Booking < ApplicationRecord
  resourcify
  belongs_to :user
  belongs_to :sharespace

  has_many :reviews, as: :reviewable

  after_create :tasks_on_create

  def tasks_on_create
    cost_days_math
    set_paid_status
    set_reviewed_status
  end

  private

  def set_paid_status
    if self.total_cost == 0 or self.total_cost == nil
      self.update(paid: true)
    else
      self.update(paid: false)
    end
  end

  def set_reviewed_status
    self.update(host_reviewed: false, user_reviewed: false) if self != nil
  end

  def cost_days_math
    total_days = (self.date_to - self.date_from).to_i + 1
    total_cost = self.sharespace.cost * total_days if self.sharespace.cost != nil
    self.update(total_days: total_days, total_cost: total_cost)
  end


end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :sharespace_venue
end

app/models/industry.rb
class Industry < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  belongs_to :industry
end

app/models/perk.rb
class Perk < ApplicationRecord
  belongs_to :sharespace_venue
end

app/models/photo.rb
class Photo < ApplicationRecord
  resourcify
  mount_uploader :image, PhotoImageUploader
  belongs_to :photoable, polymorphic: true, optional: true

  after_create :tasks

  def tasks
    profile_check
  end

  def profile_check
      if self.photoable.photos.count <= 1
        self.photoable.update(profile_photo: self.id)
      end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  resourcify
  belongs_to :reviewable, polymorphic: true, optional: true
  belongs_to :reference, polymorphic: true, optional: true
  after_create :tasks


  private
  def tasks
    set_reviewed_status
  end

  def set_reviewed_status
    if self.reference_type == 'Booking' && self.reference != nil
      self.reference.update(host_reviewed: true) if self.reviewable_type == 'SharespaceVenue'
      self.reference.update(user_reviewed: true) if self.reviewable_type == 'User'
    end
  end

end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/school.rb
class School < ApplicationRecord
end

app/models/sharespace.rb
class Sharespace < ApplicationRecord
  resourcify
  belongs_to :sharespace_venue
  has_many :photos, as: :photoable
  has_many :bookings


end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :address, as: :addressable

  has_many :photos, as: :photoable
  has_many :reviews, as: :reviewable
  has_many :sharespace_venues
  has_many :bookings
  has_many :collab_space_listings

  after_create :tasks


# These next methods set what the user can and cannot do.
  def admin_only
    self.has_role?(:admin)
  end

  def can_create?
    self.has_role?(:admin) || self.has_role?(:basic)
  end

  def owner?(owner)
    self.has_role?(:admin) || owner == self
  end

  def can_update?(object)
    self.has_role?(:admin) || (self.has_role?(:basic) && object.user == self)
  end

  def can_destroy?(object)
    self.has_role?(:admin) or (self.has_role?(:basic) && object.user == self) or self.has_role?(:moderator)
  end

  def fullname
    if first_name && last_name != nil
      "#{first_name} #{last_name}"
    elsif first_name != nil && last_name == nil
      "#{first_name}"
    elsif first_name == nil && last_name != nil
      "#{last_name}"
    else
      "User has no name."
   end
  end



  private
# This method runs multiple methods for the "after_create" method that runs the methods once a new user has signed up.
  def tasks
    set_address
    set_role
    UserNotifierMailer.send_signup_email(self).deliver
  end

# Sets an empty address for each new user which they can update and fill out at a later date.
  def set_address
    self.build_address.save
  end

# Adds a basic role with limited functions to a new user. Currently basic can do anything but in the futureI plan to incorporate "premium" membership roles (add_role :premium_member) if they pay a subscription.
  def set_role
    self.add_role :basic
  end



end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/form_helper.rb
module FormHelper
  def set_listing_address(collab_space)
    collab_space.address ||= Address.new
    collab_space
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareSpace</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <!-- CSS Normalizer  -->
    <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css' %>
    <%= stylesheet_link_tag    'https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places' %>

    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.js' %>
    <%= javascript_include_tag 'https://code.jquery.com/ui/1.12.1/jquery-ui.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <div class="nav_box">
      <%= link_to 'Home', root_path, class: "home" %>
      <nav class="navbar" id="nav_one">
        <%= link_to 'Share Spaces', sharespace_venues_path, class: "sharespace_nav" %>
        <%= link_to 'Logout', destroy_user_session_path, class: "user_align justify-end", method: :delete if user_signed_in? %>
        <%= link_to 'Login', new_user_session_path, class: "user_align justify-end" if !user_signed_in? %>
        <%= link_to "Profile", profile_url, class: "profile user_align" if user_signed_in? %>
        <%= link_to 'Sign Up', new_user_registration_path, class: "user_align" if !user_signed_in? %>
        <%= link_to 'Your Booking', reserved_booking_path, class: "booking" if user_signed_in? && (current_user.bookings.count >= 1 && current_user.bookings.last.paid == false) %>
        <%= link_to 'Admin', admin_url, class: "admin" if user_signed_in? && current_user.admin_only %>
      </nav>
      <%= link_to 'Share Spaces', sharespace_venues_path, class: "sharespace_title" %>
      <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
    </div>
    <nav class="navbar" id="nav_two">
      <%= link_to 'Share Spaces', sharespace_venues_path, class: "sharespace_nav" %>
      <%= link_to 'Logout', destroy_user_session_path, class: "user_align justify-end", method: :delete if user_signed_in? %>
      <%= link_to 'Login', new_user_session_path, class: "user_align justify-end" if !user_signed_in? %>
      <%= link_to "Profile", profile_url, class: "profile user_align" if user_signed_in? %>
      <%= link_to 'Sign Up', new_user_registration_path, class: "user_align" if !user_signed_in? %>
      <%= link_to 'Your Booking', reserved_booking_path, class: "booking" if user_signed_in? && (current_user.bookings.count >= 1 && current_user.bookings.last.paid == false) %>
      <%= link_to 'Admin', admin_url, class: "admin" if user_signed_in? && current_user.admin_only %>
    </nav>

    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </body>
</html>